export const GET_USER_POSITION_FETCHING = 'GET_USER_POSITION_FETCHING';
export const GET_USER_POSITION_FETCHED = 'GET_USER_POSITION_FETCHED';
export const GET_USER_POSITION_ERROR = 'GET_USER_POSITION_ERROR';